# -*- coding: utf-8 -*-
"""
ArcPy verification script for SHP/GDB output generated by jisig-bpoint-converter.
Tests whether the EXE's output files are valid ArcGIS-readable data.
"""
import os
import sys
import arcpy

TEMP_DIR = os.environ.get("TEMP", os.environ.get("TMP", "."))
SHP_DIR = os.path.join(TEMP_DIR, "jisig_debug_test")
GDB_DIR = os.path.join(TEMP_DIR, "jisig_debug_gdb")
GPKG_DIR = os.path.join(TEMP_DIR, "jisig_arcpy_verify")
PROJECT_DIR = r"C:\Users\Administrator\Documents\txt与gdb互转"
REF_GDB = os.path.join(PROJECT_DIR, "test_arcpy", "test.gdb")
REF_SHP_DIR = os.path.join(PROJECT_DIR, "test_arcpy", "std_shp")

PASS = 0
FAIL = 0
SKIP = 0

def report(label, ok, detail=""):
    global PASS, FAIL
    status = "PASS" if ok else "FAIL"
    if ok:
        PASS += 1
    else:
        FAIL += 1
    suffix = f"  ({detail})" if detail else ""
    print(f"  [{status}] {label}{suffix}")


def verify_ref_gdb():
    """Verify reference GDB (ArcPy-generated) is readable."""
    print("\n=== Reference GDB Verification (test_arcpy/test.gdb) ===")
    report("Reference GDB exists", os.path.exists(REF_GDB))

    if not os.path.exists(REF_GDB):
        return

    arcpy.env.workspace = REF_GDB
    feature_classes = arcpy.ListFeatureClasses()
    report("Reference GDB has 5 feature classes", len(feature_classes) == 5,
           f"found: {feature_classes}")

    for fc in sorted(feature_classes):
        desc = arcpy.Describe(fc)
        report(f"  {fc} is Polygon", desc.shapeType == "Polygon")
        count = int(arcpy.management.GetCount(fc)[0])
        report(f"  {fc} has 1 feature", count == 1, f"count={count}")

    arcpy.env.workspace = None


def verify_ref_shp():
    """Verify reference SHP files (ArcPy-generated) are readable."""
    print("\n=== Reference SHP Verification (test_arcpy/std_shp/) ===")
    for i in range(5):
        shp_name = f"plot_{i:03d}.shp"
        shp_path = os.path.join(REF_SHP_DIR, shp_name)
        report(f"{shp_name} exists", os.path.exists(shp_path))

        if os.path.exists(shp_path):
            desc = arcpy.Describe(shp_path)
            report(f"  {shp_name} shapeType is Polygon", desc.shapeType == "Polygon")
            count = int(arcpy.management.GetCount(shp_path)[0])
            report(f"  {shp_name} has 1 feature", count == 1, f"count={count}")


def verify_generated_shp():
    """Verify SHP generated by EXE logic (debug_output_test)."""
    print("\n=== Generated SHP Verification ===")
    shp_path = os.path.join(SHP_DIR, "debug_output.shp")
    report("SHP file exists", os.path.exists(shp_path), shp_path)

    if not os.path.exists(shp_path):
        return

    desc = arcpy.Describe(shp_path)
    report("Shape type is Polygon", desc.shapeType == "Polygon", desc.shapeType)
    report("Spatial reference exists", desc.spatialReference is not None)

    sr = desc.spatialReference
    if sr:
        report("CRS name contains CGCS2000",
               "CGCS2000" in sr.name or "2000" in sr.name,
               sr.name)

    # Read all rows
    fields = [f.name for f in arcpy.ListFields(shp_path)]
    expected_fields = ["DKMC", "DKBH", "MJ", "DKYT", "TFH", "DLBM"]
    for ef in expected_fields:
        report(f"Field '{ef}' exists", ef in fields, f"found: {fields}")

    row_count = 0
    with arcpy.da.SearchCursor(shp_path, ["SHAPE@", "DKMC", "MJ"]) as cursor:
        for row in cursor:
            row_count += 1
            geom = row[0]
            dkmc = row[1]
            mj = row[2]

            report("Geometry is not None", geom is not None)
            report("Geometry has area > 0", geom.area > 0, f"area={geom.area:.2f}")

            # Coordinate range check
            # CGCS2000 3-degree zone 38: X may have zone prefix (38xxxxxxx) or raw easting
            extent = geom.extent
            x_min = extent.XMin
            # Accept both raw easting (~300000) and zone-prefixed (~38300000)
            x_ok = (100000 < x_min < 2000000) or (38000000 < x_min < 39000000)
            report("X coordinate in reasonable range (CGCS2000 GK Zone 38)",
                   x_ok, f"XMin={x_min:.2f}")
            report("Y coordinate in reasonable range",
                   2000000 < extent.YMin < 5000000,
                   f"YMin={extent.YMin:.2f}")

            report("DKMC is not empty", dkmc is not None and len(str(dkmc).strip()) > 0, str(dkmc))
            report("MJ (area) is numeric", mj is not None, str(mj))

    report("Row count is 1", row_count == 1, f"got {row_count}")

    # Check companion files
    for ext in [".dbf", ".shx", ".prj", ".cpg"]:
        companion = os.path.join(SHP_DIR, "debug_output" + ext)
        report(f"Companion file {ext} exists", os.path.exists(companion))


def verify_generated_gdb():
    """Verify GDB generated by EXE logic (debug_output_test)."""
    print("\n=== Generated GDB Verification ===")
    gdb_path = os.path.join(GDB_DIR, "debug_gdb.gdb")
    report("GDB directory exists", os.path.exists(gdb_path), gdb_path)

    if not os.path.exists(gdb_path):
        return

    # Check file structure
    gdb_files = os.listdir(gdb_path)
    report("GDB has gdb marker", "gdb" in gdb_files)
    report("GDB has system catalog (a00000001.gdbtable)",
           "a00000001.gdbtable" in gdb_files)

    # Check if it has the full system catalog structure needed by ArcPy
    has_gdbindexes = any(f.endswith(".gdbindexes") for f in gdb_files)
    has_atx = any(f.endswith(".atx") for f in gdb_files)
    has_horizon = any(f.endswith(".horizon") for f in gdb_files)
    has_spx = any(f.endswith(".spx") for f in gdb_files)

    report("GDB has .gdbindexes files", has_gdbindexes)
    report("GDB has .atx index files", has_atx)
    report("GDB has .horizon files", has_horizon)
    report("GDB has .spx spatial index files", has_spx)

    # Try ArcPy read
    arcpy.env.workspace = gdb_path
    feature_classes = arcpy.ListFeatureClasses()

    if len(feature_classes) > 0:
        report("ArcPy can list feature classes", True, f"found: {feature_classes}")
        for fc in feature_classes:
            desc = arcpy.Describe(fc)
            report(f"  {fc} shapeType is Polygon", desc.shapeType == "Polygon")
            count = int(arcpy.management.GetCount(fc)[0])
            report(f"  {fc} has 1 feature", count == 1, f"count={count}")
    else:
        report("ArcPy can list feature classes", False,
               "Empty - GDB structure may be incomplete (minimal OpenFileGDB)")
        print("  NOTE: The EXE uses minimal OpenFileGDB write. ArcPy requires full system catalog.")
        print("  This is a known limitation - the GDB is readable by the EXE but not by ArcPy.")

    arcpy.env.workspace = None


def verify_generated_gpkg():
    """Verify GPKG generated by EXE logic (debug/release smoke)."""
    print("\n=== Generated GPKG Verification ===")
    gpkg_path = os.path.join(GPKG_DIR, "plot_000.gpkg")
    report("GPKG file exists", os.path.exists(gpkg_path), gpkg_path)

    if not os.path.exists(gpkg_path):
        return

    try:
        desc = arcpy.Describe(gpkg_path)
        report("GPKG Describe succeeds", desc is not None)
        if desc:
            report("GPKG shapeType is Polygon", getattr(desc, "shapeType", "") == "Polygon", getattr(desc, "shapeType", ""))
            sr = getattr(desc, "spatialReference", None)
            report("Spatial reference exists", sr is not None)
            if sr:
                report("CRS name contains CGCS2000 or zone code",
                       "CGCS2000" in sr.name or "4526" in sr.name or "4547" in sr.name,
                       sr.name)
    except Exception as exc:
        report("GPKG Describe succeeds", False, str(exc))
        return

    try:
        arcpy.env.workspace = gpkg_path
        feature_classes = arcpy.ListFeatureClasses()
        report("ArcPy can list feature classes", len(feature_classes) > 0, f"found: {feature_classes}")
        for fc in feature_classes:
            desc = arcpy.Describe(fc)
            report(f"  {fc} shapeType is Polygon", desc.shapeType == "Polygon", desc.shapeType)
            count = int(arcpy.management.GetCount(fc)[0])
            report(f"  {fc} has at least 1 feature", count > 0, f"count={count}")
            with arcpy.da.SearchCursor(fc, ["SHAPE@"]) as cursor:
                first = next(cursor, None)
                report(f"  {fc} geometry is not None", first is not None and first[0] is not None)
    except Exception as exc:
        report("ArcPy can read GPKG as feature classes", False, str(exc))
    finally:
        arcpy.env.workspace = None


if __name__ == "__main__":
    print("ArcPy Verification for jisig-bpoint-converter output")
    print(f"ArcPy version: {arcpy.GetInstallInfo()['Version']}")
    print(f"Project dir: {PROJECT_DIR}")

    verify_ref_gdb()
    verify_ref_shp()
    verify_generated_shp()
    verify_generated_gdb()
    verify_generated_gpkg()

    print(f"\n{'='*50}")
    print(f"Results: {PASS} passed, {FAIL} failed, {PASS+FAIL} total")

    if FAIL > 0:
        print("SOME TESTS FAILED")
        sys.exit(1)
    else:
        print("ALL TESTS PASSED")
        sys.exit(0)
